spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres

spring.application.name = helpdesk
spring.profiles.active = dev
server.port = 8080
spring.datasource.url = jdbc:postgresql://localhost:5432/helpdesk
spring.datasource.username = postgres
spring.datasource.password = 123
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = none
spring.jpa.hibernate.naming.implicit-strategy = org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.jpa.properties.hibernate.format_sql = true

# Disable the H2 console
#spring.h2.console.enabled=false

# Exclude H2-related auto-configuration
#spring.autoconfigure.exclude = org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
